export default [
  {
    startProjectList: 4,
    commissionRat: 0,
    lxProjectList: 3,
    finishRat: 19.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 50.0,
    planInvestment: 39.42,
    noLxProjectList: 3,
    noCommissionList: 4,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 20.0,
    noStartProjectList: 4,
    groupValue: '高新区20212',
    realInvestment: 7.82,
    productionRat: 0
  },

  {
    startProjectList: 15,
    commissionRat: 53.0,
    lxProjectList: 15,
    finishRat: 44.0,
    commissionList: 8,
    productionList: 0,
    filingRate: 68.0,
    planInvestment: 188.99,
    noLxProjectList: 7,
    noCommissionList: 7,
    startRate: 93.0,
    noProductionList: 8,
    industryRat: 80.0,
    noStartProjectList: 15,
    groupValue: '高新区20211',
    realInvestment: 84.22,
    productionRat: 0
  },
  {
    startProjectList: 6,
    commissionRat: 0,
    lxProjectList: 1,
    finishRat: 20.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 100.0,
    planInvestment: 35.45,
    noLxProjectList: 0,
    noCommissionList: 6,
    startRate: 54.0,
    noProductionList: 0,
    industryRat: 0,
    noStartProjectList: 6,
    groupValue: '顾山镇20221',
    realInvestment: 7.42,
    productionRat: 0
  },
  {
    startProjectList: 1,
    commissionRat: 0,
    lxProjectList: 1,
    finishRat: 100.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 100.0,
    planInvestment: 1.3,
    noLxProjectList: 0,
    noCommissionList: 1,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 20.0,
    noStartProjectList: 1,
    groupValue: '青阳镇20212',
    realInvestment: 1.3,
    productionRat: 0
  },
  {
    startProjectList: 4,
    commissionRat: 25.0,
    lxProjectList: 0,
    finishRat: 24.0,
    commissionList: 1,
    productionList: 0,
    filingRate: 0,
    planInvestment: 11.13,
    noLxProjectList: 1,
    noCommissionList: 3,
    startRate: 100.0,
    noProductionList: 1,
    industryRat: 80.0,
    noStartProjectList: 4,
    groupValue: '青阳镇20211',
    realInvestment: 2.68,
    productionRat: 0
  },
  {
    startProjectList: 1,
    commissionRat: 0,
    lxProjectList: 2,
    finishRat: 0.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 100.0,
    planInvestment: 4.85,
    noLxProjectList: 0,
    noCommissionList: 1,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 11.0,
    noStartProjectList: 1,
    groupValue: '靖江园区20212',
    realInvestment: 0.0,
    productionRat: 0
  },
  {
    startProjectList: 8,
    commissionRat: 62.0,
    lxProjectList: 4,
    finishRat: 33.0,
    commissionList: 5,
    productionList: 0,
    filingRate: 100.0,
    planInvestment: 35.31,
    noLxProjectList: 0,
    noCommissionList: 3,
    startRate: 100.0,
    noProductionList: 5,
    industryRat: 88.0,
    noStartProjectList: 8,
    groupValue: '靖江园区20211',
    realInvestment: 11.66,
    productionRat: 0
  },
  {
    startProjectList: 2,
    commissionRat: 100.0,
    lxProjectList: 0,
    finishRat: 0.0,
    commissionList: 2,
    productionList: 0,
    filingRate: 0,
    planInvestment: 14.0,
    noLxProjectList: 0,
    noCommissionList: 0,
    startRate: 100.0,
    noProductionList: 2,
    industryRat: 50.0,
    noStartProjectList: 2,
    groupValue: '顾山镇20212',
    realInvestment: 0.0,
    productionRat: 0
  },
  {
    startProjectList: 1,
    commissionRat: 0,
    lxProjectList: 0,
    finishRat: 0.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 0,
    planInvestment: 15.0,
    noLxProjectList: 0,
    noCommissionList: 1,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 12.0,
    noStartProjectList: 1,
    groupValue: '周庄镇20222',
    realInvestment: 0.0,
    productionRat: 0
  },
  {
    startProjectList: 2,
    commissionRat: 100.0,
    lxProjectList: 5,
    finishRat: 89.0,
    commissionList: 2,
    productionList: 0,
    filingRate: 100.0,
    planInvestment: 6.68,
    noLxProjectList: 0,
    noCommissionList: 0,
    startRate: 100.0,
    noProductionList: 2,
    industryRat: 50.0,
    noStartProjectList: 2,
    groupValue: '顾山镇20211',
    realInvestment: 6.0,
    productionRat: 0
  },
  {
    startProjectList: 6,
    commissionRat: 16.0,
    lxProjectList: 1,
    finishRat: 2.0,
    commissionList: 1,
    productionList: 0,
    filingRate: 100.0,
    planInvestment: 67.24,
    noLxProjectList: 0,
    noCommissionList: 5,
    startRate: 85.0,
    noProductionList: 1,
    industryRat: 87.0,
    noStartProjectList: 6,
    groupValue: '周庄镇20221',
    realInvestment: 1.72,
    productionRat: 0
  },
  {
    startProjectList: 9,
    commissionRat: 22.0,
    lxProjectList: 7,
    finishRat: 56.0,
    commissionList: 2,
    productionList: 0,
    filingRate: 50.0,
    planInvestment: 19.15,
    noLxProjectList: 7,
    noCommissionList: 7,
    startRate: 100.0,
    noProductionList: 2,
    industryRat: 69.0,
    noStartProjectList: 9,
    groupValue: '新桥镇20211',
    realInvestment: 10.88,
    productionRat: 0
  },
  {
    startProjectList: 1,
    commissionRat: 0,
    lxProjectList: 0,
    finishRat: 0.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 0,
    planInvestment: 40.0,
    noLxProjectList: 0,
    noCommissionList: 1,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 25.0,
    noStartProjectList: 1,
    groupValue: '徐霞客镇20212',
    realInvestment: 0.0,
    productionRat: 0
  },
  {
    startProjectList: 4,
    commissionRat: 0,
    lxProjectList: 4,
    finishRat: 2.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 100.0,
    planInvestment: 21.6,
    noLxProjectList: 0,
    noCommissionList: 4,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 30.0,
    noStartProjectList: 4,
    groupValue: '新桥镇20212',
    realInvestment: 0.52,
    productionRat: 0
  },
  {
    startProjectList: 2,
    commissionRat: 50.0,
    lxProjectList: 12,
    finishRat: 41.0,
    commissionList: 1,
    productionList: 0,
    filingRate: 100.0,
    planInvestment: 5.7,
    noLxProjectList: 0,
    noCommissionList: 1,
    startRate: 66.0,
    noProductionList: 1,
    industryRat: 75.0,
    noStartProjectList: 2,
    groupValue: '徐霞客镇20211',
    realInvestment: 2.36,
    productionRat: 0
  },
  {
    startProjectList: 4,
    commissionRat: 50.0,
    lxProjectList: 0,
    finishRat: 29.0,
    commissionList: 2,
    productionList: 0,
    filingRate: 0,
    planInvestment: 9.17,
    noLxProjectList: 0,
    noCommissionList: 2,
    startRate: 100.0,
    noProductionList: 2,
    industryRat: 0,
    noStartProjectList: 4,
    groupValue: '月城镇20211',
    realInvestment: 2.75,
    productionRat: 0
  },
  {
    startProjectList: 9,
    commissionRat: 11.0,
    lxProjectList: 2,
    finishRat: 11.0,
    commissionList: 1,
    productionList: 0,
    filingRate: 66.0,
    planInvestment: 55.38,
    noLxProjectList: 1,
    noCommissionList: 8,
    startRate: 81.0,
    noProductionList: 1,
    industryRat: 0,
    noStartProjectList: 9,
    groupValue: '云亭街道20221',
    realInvestment: 6.37,
    productionRat: 0
  },
  {
    startProjectList: 3,
    commissionRat: 0,
    lxProjectList: 2,
    finishRat: 35.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 40.0,
    planInvestment: 11.1,
    noLxProjectList: 3,
    noCommissionList: 3,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 60.0,
    noStartProjectList: 3,
    groupValue: '青阳镇20221',
    realInvestment: 3.92,
    productionRat: 0
  },
  {
    startProjectList: 4,
    commissionRat: 25.0,
    lxProjectList: 3,
    finishRat: 20.0,
    commissionList: 1,
    productionList: 0,
    filingRate: 100.0,
    planInvestment: 59.68,
    noLxProjectList: 0,
    noCommissionList: 3,
    startRate: 57.0,
    noProductionList: 1,
    industryRat: 77.0,
    noStartProjectList: 4,
    groupValue: '澄江街道20222',
    realInvestment: 12.48,
    productionRat: 0
  },
  {
    startProjectList: 2,
    commissionRat: 0,
    lxProjectList: 0,
    finishRat: 9.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 0,
    planInvestment: 52.47,
    noLxProjectList: 0,
    noCommissionList: 2,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 40.0,
    noStartProjectList: 2,
    groupValue: '青阳镇20222',
    realInvestment: 4.95,
    productionRat: 0
  },
  {
    startProjectList: 0,
    commissionRat: 0,
    lxProjectList: 0,
    finishRat: 0.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 0,
    planInvestment: 1.0,
    noLxProjectList: 0,
    noCommissionList: 0,
    startRate: 0,
    noProductionList: 0,
    industryRat: 22.0,
    noStartProjectList: 0,
    groupValue: '澄江街道20221',
    realInvestment: 0.0,
    productionRat: 0
  },
  {
    startProjectList: 3,
    commissionRat: 33.0,
    lxProjectList: 4,
    finishRat: 5.0,
    commissionList: 1,
    productionList: 0,
    filingRate: 66.0,
    planInvestment: 99.96,
    noLxProjectList: 2,
    noCommissionList: 2,
    startRate: 30.0,
    noProductionList: 1,
    industryRat: 66.0,
    noStartProjectList: 3,
    groupValue: '靖江园区20221',
    realInvestment: 5.83,
    productionRat: 0
  },
  {
    startProjectList: 1,
    commissionRat: 0,
    lxProjectList: 2,
    finishRat: 9.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 66.0,
    planInvestment: 14.45,
    noLxProjectList: 1,
    noCommissionList: 1,
    startRate: 20.0,
    noProductionList: 0,
    industryRat: 33.0,
    noStartProjectList: 1,
    groupValue: '靖江园区20222',
    realInvestment: 1.35,
    productionRat: 0
  },
  {
    startProjectList: 3,
    commissionRat: 33.0,
    lxProjectList: 0,
    finishRat: 58.0,
    commissionList: 1,
    productionList: 0,
    filingRate: 0,
    planInvestment: 9.68,
    noLxProjectList: 0,
    noCommissionList: 2,
    startRate: 75.0,
    noProductionList: 1,
    industryRat: 0,
    noStartProjectList: 3,
    groupValue: '周庄镇20211',
    realInvestment: 5.66,
    productionRat: 0
  },
  {
    startProjectList: 0,
    commissionRat: 0,
    lxProjectList: 1,
    finishRat: 0.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 100.0,
    planInvestment: 0.43,
    noLxProjectList: 0,
    noCommissionList: 0,
    startRate: 0,
    noProductionList: 0,
    industryRat: 5.0,
    noStartProjectList: 0,
    groupValue: '徐霞客镇20222',
    realInvestment: 0.0,
    productionRat: 0
  },
  {
    startProjectList: 13,
    commissionRat: 7.0,
    lxProjectList: 2,
    finishRat: 6.0,
    commissionList: 1,
    productionList: 0,
    filingRate: 66.0,
    planInvestment: 64.76,
    noLxProjectList: 1,
    noCommissionList: 12,
    startRate: 76.0,
    noProductionList: 1,
    industryRat: 94.0,
    noStartProjectList: 13,
    groupValue: '徐霞客镇20221',
    realInvestment: 3.99,
    productionRat: 0
  },
  {
    startProjectList: 1,
    commissionRat: 0,
    lxProjectList: 0,
    finishRat: 0.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 0,
    planInvestment: 4.04,
    noLxProjectList: 0,
    noCommissionList: 1,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 0,
    noStartProjectList: 1,
    groupValue: '江阴市20211',
    realInvestment: 0.0,
    productionRat: 0
  },
  {
    startProjectList: 1,
    commissionRat: 0,
    lxProjectList: 0,
    finishRat: 0.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 0,
    planInvestment: 1.12,
    noLxProjectList: 0,
    noCommissionList: 1,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 33.0,
    noStartProjectList: 1,
    groupValue: '月城镇20222',
    realInvestment: 0.0,
    productionRat: 0
  },
  {
    startProjectList: 2,
    commissionRat: 50.0,
    lxProjectList: 0,
    finishRat: 0.0,
    commissionList: 1,
    productionList: 0,
    filingRate: 0,
    planInvestment: 11.1,
    noLxProjectList: 0,
    noCommissionList: 1,
    startRate: 100.0,
    noProductionList: 1,
    industryRat: 66.0,
    noStartProjectList: 2,
    groupValue: '月城镇20221',
    realInvestment: 0.0,
    productionRat: 0
  },
  {
    startProjectList: 1,
    commissionRat: 0,
    lxProjectList: 0,
    finishRat: 54.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 0,
    planInvestment: 7.62,
    noLxProjectList: 0,
    noCommissionList: 1,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 14.0,
    noStartProjectList: 1,
    groupValue: '云亭街道20212',
    realInvestment: 4.12,
    productionRat: 0
  },
  {
    startProjectList: 6,
    commissionRat: 0,
    lxProjectList: 4,
    finishRat: 51.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 100.0,
    planInvestment: 22.98,
    noLxProjectList: 0,
    noCommissionList: 6,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 85.0,
    noStartProjectList: 6,
    groupValue: '云亭街道20211',
    realInvestment: 11.88,
    productionRat: 0
  },
  {
    startProjectList: 2,
    commissionRat: 0,
    lxProjectList: 0,
    finishRat: 87.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 0,
    planInvestment: 3.9,
    noLxProjectList: 0,
    noCommissionList: 2,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 28.0,
    noStartProjectList: 2,
    groupValue: '祝塘镇20212',
    realInvestment: 3.4,
    productionRat: 0
  },
  {
    startProjectList: 5,
    commissionRat: 40.0,
    lxProjectList: 0,
    finishRat: 57.0,
    commissionList: 2,
    productionList: 0,
    filingRate: 0,
    planInvestment: 29.84,
    noLxProjectList: 0,
    noCommissionList: 3,
    startRate: 100.0,
    noProductionList: 2,
    industryRat: 71.0,
    noStartProjectList: 5,
    groupValue: '祝塘镇20211',
    realInvestment: 17.01,
    productionRat: 0
  },
  {
    startProjectList: 28,
    commissionRat: 39.0,
    lxProjectList: 0,
    finishRat: 34.0,
    commissionList: 11,
    productionList: 0,
    filingRate: 0,
    planInvestment: 270.91,
    noLxProjectList: 0,
    noCommissionList: 17,
    startRate: 100.0,
    noProductionList: 11,
    industryRat: 77.0,
    noStartProjectList: 28,
    groupValue: '临港经济开发区20211',
    realInvestment: 93.67,
    productionRat: 0
  },
  {
    startProjectList: 8,
    commissionRat: 25.0,
    lxProjectList: 0,
    finishRat: 14.0,
    commissionList: 2,
    productionList: 0,
    filingRate: 0,
    planInvestment: 98.6,
    noLxProjectList: 0,
    noCommissionList: 6,
    startRate: 100.0,
    noProductionList: 2,
    industryRat: 22.0,
    noStartProjectList: 8,
    groupValue: '临港经济开发区20212',
    realInvestment: 13.93,
    productionRat: 0
  },
  {
    startProjectList: 5,
    commissionRat: 40.0,
    lxProjectList: 0,
    finishRat: 12.0,
    commissionList: 2,
    productionList: 0,
    filingRate: 0,
    planInvestment: 86.42,
    noLxProjectList: 0,
    noCommissionList: 3,
    startRate: 100.0,
    noProductionList: 2,
    industryRat: 0,
    noStartProjectList: 5,
    groupValue: 'null20221',
    realInvestment: 10.83,
    productionRat: 0
  },
  {
    startProjectList: 5,
    commissionRat: 100.0,
    lxProjectList: 0,
    finishRat: 32.0,
    commissionList: 5,
    productionList: 0,
    filingRate: 0,
    planInvestment: 26.2,
    noLxProjectList: 5,
    noCommissionList: 0,
    startRate: 100.0,
    noProductionList: 5,
    industryRat: 0,
    noStartProjectList: 5,
    groupValue: '长泾镇20211',
    realInvestment: 8.58,
    productionRat: 0
  },
  {
    startProjectList: 4,
    commissionRat: 0,
    lxProjectList: 0,
    finishRat: 8.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 0,
    planInvestment: 15.98,
    noLxProjectList: 0,
    noCommissionList: 4,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 0,
    noStartProjectList: 4,
    groupValue: '华士镇20221',
    realInvestment: 1.31,
    productionRat: 0
  },
  {
    startProjectList: 1,
    commissionRat: 0,
    lxProjectList: 1,
    finishRat: 87.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 100.0,
    planInvestment: 2.0,
    noLxProjectList: 0,
    noCommissionList: 1,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 0,
    noStartProjectList: 1,
    groupValue: '南闸街道20211',
    realInvestment: 1.75,
    productionRat: 0
  },
  {
    startProjectList: 24,
    commissionRat: 16.0,
    lxProjectList: 2,
    finishRat: 18.0,
    commissionList: 4,
    productionList: 0,
    filingRate: 50.0,
    planInvestment: 265.63,
    noLxProjectList: 2,
    noCommissionList: 20,
    startRate: 63.0,
    noProductionList: 4,
    industryRat: 84.0,
    noStartProjectList: 24,
    groupValue: '高新区20221',
    realInvestment: 49.96,
    productionRat: 0
  },
  {
    startProjectList: 6,
    commissionRat: 0,
    lxProjectList: 1,
    finishRat: 6.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 16.0,
    planInvestment: 41.14,
    noLxProjectList: 5,
    noCommissionList: 6,
    startRate: 85.0,
    noProductionList: 0,
    industryRat: 15.0,
    noStartProjectList: 6,
    groupValue: '高新区20222',
    realInvestment: 2.58,
    productionRat: 0
  },
  {
    startProjectList: 14,
    commissionRat: 50.0,
    lxProjectList: 4,
    finishRat: 6.0,
    commissionList: 7,
    productionList: 0,
    filingRate: 57.0,
    planInvestment: 89.9,
    noLxProjectList: 3,
    noCommissionList: 7,
    startRate: 77.0,
    noProductionList: 7,
    industryRat: 78.0,
    noStartProjectList: 14,
    groupValue: '临港经济开发区20221',
    realInvestment: 6.22,
    productionRat: 0
  },
  {
    startProjectList: 2,
    commissionRat: 0,
    lxProjectList: 3,
    finishRat: 18.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 42.0,
    planInvestment: 89.21,
    noLxProjectList: 4,
    noCommissionList: 2,
    startRate: 40.0,
    noProductionList: 0,
    industryRat: 21.0,
    noStartProjectList: 2,
    groupValue: '临港经济开发区20222',
    realInvestment: 16.45,
    productionRat: 0
  },
  {
    startProjectList: 3,
    commissionRat: 66.0,
    lxProjectList: 0,
    finishRat: 43.0,
    commissionList: 2,
    productionList: 0,
    filingRate: 0,
    planInvestment: 12.75,
    noLxProjectList: 0,
    noCommissionList: 1,
    startRate: 100.0,
    noProductionList: 2,
    industryRat: 0,
    noStartProjectList: 3,
    groupValue: '华士镇20211',
    realInvestment: 5.49,
    productionRat: 0
  },
  {
    startProjectList: 8,
    commissionRat: 0,
    lxProjectList: 1,
    finishRat: 15.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 100.0,
    planInvestment: 31.35,
    noLxProjectList: 0,
    noCommissionList: 8,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 47.0,
    noStartProjectList: 8,
    groupValue: '新桥镇20222',
    realInvestment: 4.86,
    productionRat: 0
  },
  {
    startProjectList: 3,
    commissionRat: 33.0,
    lxProjectList: 0,
    finishRat: 0.0,
    commissionList: 1,
    productionList: 0,
    filingRate: 0,
    planInvestment: 4.97,
    noLxProjectList: 2,
    noCommissionList: 2,
    startRate: 75.0,
    noProductionList: 1,
    industryRat: 0,
    noStartProjectList: 3,
    groupValue: '南闸街道20221',
    realInvestment: 0.0,
    productionRat: 0
  },
  {
    startProjectList: 1,
    commissionRat: 100.0,
    lxProjectList: 0,
    finishRat: 100.0,
    commissionList: 1,
    productionList: 0,
    filingRate: 0,
    planInvestment: 28.14,
    noLxProjectList: 0,
    noCommissionList: 0,
    startRate: 100.0,
    noProductionList: 1,
    industryRat: 0,
    noStartProjectList: 1,
    groupValue: '祝塘镇20221',
    realInvestment: 28.16,
    productionRat: 0
  },
  {
    startProjectList: 2,
    commissionRat: 0,
    lxProjectList: 0,
    finishRat: 36.0,
    commissionList: 0,
    productionList: 0,
    filingRate: 0,
    planInvestment: 4.68,
    noLxProjectList: 1,
    noCommissionList: 2,
    startRate: 100.0,
    noProductionList: 0,
    industryRat: 0,
    noStartProjectList: 2,
    groupValue: '长泾镇20221',
    realInvestment: 1.71,
    productionRat: 0
  },
  {
    startProjectList: 7,
    commissionRat: 42.0,
    lxProjectList: 2,
    finishRat: 33.0,
    commissionList: 3,
    productionList: 0,
    filingRate: 100.0,
    planInvestment: 33.44,
    noLxProjectList: 0,
    noCommissionList: 4,
    startRate: 77.0,
    noProductionList: 3,
    industryRat: 52.0,
    noStartProjectList: 7,
    groupValue: '新桥镇20221',
    realInvestment: 11.2,
    productionRat: 0
  }
]
